//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KT0720ThanhDat_61130307.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTHDN
    {
        public string SoHD { get; set; }
        public string MaHH { get; set; }
        public short SoLuong { get; set; }
        public int DonGiaNhap { get; set; }
    
        public virtual HoaDonNhap HoaDonNhap { get; set; }
        public virtual HangHoa HangHoa { get; set; }
    }
}
