//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KT0720LeDucBinh_59130126.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class KT0720_59130126Entities : DbContext
    {
        public KT0720_59130126Entities()
            : base("name=KT0720_59130126Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LOAISP> LOAISP { get; set; }
        public virtual DbSet<SANPHAM> SANPHAM { get; set; }
    
        public virtual int TimKiemThanhVien(string maSP, string maLSP)
        {
            var maSPParameter = maSP != null ?
                new ObjectParameter("MaSP", maSP) :
                new ObjectParameter("MaSP", typeof(string));
    
            var maLSPParameter = maLSP != null ?
                new ObjectParameter("MaLSP", maLSP) :
                new ObjectParameter("MaLSP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TimKiemThanhVien", maSPParameter, maLSPParameter);
        }
    }
}
