//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TINTUC
    {
        public string MATT { get; set; }
        public string TIEUDE { get; set; }
        public string NGONNGU { get; set; }
        public string NGUOIDANG { get; set; }
        public Nullable<System.DateTime> NGAYDANG { get; set; }
        public string ANHDAIDIEN { get; set; }
        public string GHICHU { get; set; }
        public string MALTT { get; set; }
    
        public virtual LOAITINTUC LOAITINTUC { get; set; }
    }
}
