//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KT2020_59136106.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class DOCGIA
    {
        [Required(ErrorMessage = "Vui lòng nhập thông tin!")]
        [DisplayName("Mã Độc Giả")]
        public string MaDG { get; set; }
        [DisplayName("Họ Độc Giả")]
        public string HoDG { get; set; }
        [DisplayName("Tên Độc Giả")]
        public string TenDG { get; set; }
        [DisplayName("Ngày sinh")]
        public System.DateTime NgaySinh { get; set; }
        [DisplayName("Giới tính")]
        public Nullable<bool> GioiTinh { get; set; }

        public string Email { get; set; }
        [DisplayName("Ảnh")]
        public string Anh { get; set; }
        [DisplayName("Mã Loại Độc Giả")]
        public string MaLDG { get; set; }
    
        public virtual LOAIDG LOAIDG { get; set; }
    }
}
