//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace truonglol.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class LOAIQUANAO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOAIQUANAO()
        {
            this.QUANAO = new HashSet<QUANAO>();
        }
        [DisplayName("Mã LQA")]
        public string MaLQA { get; set; }
        [DisplayName("Tên LQA")]
        public string TenLQA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QUANAO> QUANAO { get; set; }
    }
}
