//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace truonglol.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class QUANAO
    {
        [Required(ErrorMessage ="Vui lòng nhập thông tin!")]
        [DisplayName("Mã Quần Áo")]
        public string MAQA { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập thông tin!")]
        [DisplayName("Tên Quần Áo")]
        public string TenQA { get; set; }
        [DisplayName("Mô Tả")]
        public string MOTA { get; set; }
        [DisplayName("Đơn Giá")]
        public int DonGia { get; set; }
        [DisplayName("Xuất Xứ")]
        public Nullable<bool> XuatXu { get; set; }
        [DisplayName("Ảnh")]
        public string Anh { get; set; }
        [DisplayName("Mã Loại Quần Áo")]
        public string MaLQA { get; set; }
    
        public virtual LOAIQUANAO LOAIQUANAO { get; set; }
    }
}
