//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KT100720_59131885.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class KT100720_59131885Entities : DbContext
    {
        public KT100720_59131885Entities()
            : base("name=KT100720_59131885Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LoaiTaiSan> LoaiTaiSan { get; set; }
        public virtual DbSet<TaiSan> TaiSan { get; set; }
    
        public virtual int TimKiemDocGia(string tenTS, string giaMin, string giaMax)
        {
            var tenTSParameter = tenTS != null ?
                new ObjectParameter("TenTS", tenTS) :
                new ObjectParameter("TenTS", typeof(string));
    
            var giaMinParameter = giaMin != null ?
                new ObjectParameter("GiaMin", giaMin) :
                new ObjectParameter("GiaMin", typeof(string));
    
            var giaMaxParameter = giaMax != null ?
                new ObjectParameter("GiaMax", giaMax) :
                new ObjectParameter("GiaMax", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TimKiemDocGia", tenTSParameter, giaMinParameter, giaMaxParameter);
        }
    }
}
